<?php declare(strict_types=1);

namespace Contributte\Tracy\Templates\NavigationPanel;

$getRowspan = function (array $array): int {
	$size = 0;
	foreach ($array as $content) {
		if (is_array($content)) { //presenters
			$size += count($content);
		} else { //actions
			$size++;
		}
	}
	return $size;
}

?>
<h1>Navigation</h1>

<div class="tracy-inner">
	<table style="width: 100%;">
		<thead>
		<tr>
			<th>Module</th>
			<th>Presenter</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
		<?php $moduleRowspan = 1; ?>
		<?php $presenterRowspan = 1; ?>
		<?php foreach ($tree as $module => $presenters): ?>
			<?php foreach ($presenters as $presenter => $actions): ?>
				<?php foreach ($actions as $action => $url): ?>
					<tr>

						<?php if ($moduleRowspan === 1): ?>
							<?php $moduleRowspan = $getRowspan($presenters) ?>
							<td rowspan="<?php echo $moduleRowspan; ?>"><?php echo $module; ?></td>
						<?php else: ?>
							<?php $moduleRowspan = $moduleRowspan - 1; ?>
						<?php endif; ?>


						<?php if ($presenterRowspan === 1): ?>

							<?php $presenterRowspan = $getRowspan($actions); ?>
							<td rowspan="<?php echo $presenterRowspan ?>">
								<a href="<?php echo $url; ?>">
									<?php echo $presenter; ?>
								</a>
							</td>

						<?php else: ?>
							<?php $presenterRowspan = $presenterRowspan - 1; ?>
						<?php endif; ?>


						<td>
							<a href="<?php echo $url; ?>">
								<?php echo $action; ?>
							</a>
						</td>

					</tr>
				<?php endforeach; ?>
			<?php endforeach; ?>
		<?php endforeach; ?>
		</tbody>
	</table>
</div>
